name: Daily Tag Site

env:
  # Required, URL to upstream (fork base)
  UPSTREAM_URL: 'https://github.com/umijs/umi.git'
  # Required, token to authenticate bot, could use ${{ secrets.GITHUB_TOKEN }}
  # Over here, we use a PAT instead to authenticate workflow file changes.
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  # Optional, defaults to main
  UPSTREAM_BRANCH: 'master'
  # Optional, defaults to UPSTREAM_BRANCH
  DOWNSTREAM_BRANCH: ''
  # Optional fetch arguments
  FETCH_ARGS: ''
  # Optional merge arguments
  MERGE_ARGS: '--no-ff'
  # Optional push arguments
  PUSH_ARGS: ''
  # Optional toggle to spawn time logs (keeps action active)
  SPAWN_LOGS: 'false' # "true" or "false"
  NODE_OPTIONS: --max-old-space-size=6144
on:
  schedule:
    - cron: '0 7 * * *' # ron on 7am every day
  # Allows manual workflow run (must in default branch to work)
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          token: ${{ env.WORKFLOW_TOKEN }}
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          fetch_args: ${{ env.FETCH_ARGS }}
          merge_args: ${{ env.MERGE_ARGS }}
          push_args: ${{ env.PUSH_ARGS }}
          spawn_logs: ${{ env.SPAWN_LOGS }}
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i
        
      - name: Add content path
        run: |
          sed -i 's/manifest: {},/manifest: {basePath: "\/mirror\/umi-next\/",}, base: "\/mirror\/umi-next\/", publicPath: "\/mirror\/umi-next\/"/' .umirc.ts
          sed -i 's/outputPath: \'..\/dist\',/outputPath: \'..\/dist\', base: "\/mirror\/umi-next\/", publicPath: "\/mirror\/umi-next\/"/' ./docs/.dumirc.ts

      - run: pnpm doc:build
      
      - name: zip zite
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r umi-next.zip dist

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::umi-next_$(date +"%Y.%m.%d_%H_%M_%S")"
 
      - name: GH Release
        # You may pin to the exact commit or the version.
        # uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: umi-next.zip
